add wave -position end  sim:/testbench/TOP0/PDP/MPC/q
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_address
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/MAR/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/MDR/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/IR/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/regs/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/special_regs/tmp/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/special_regs/src/q
add wave -position end  sim:/testbench/TOP0/PDP/DATAPATH0/special_regs/dst/q
add wave -position end  sim:/testbench/TOP0/RAM0/address
add wave -position end  sim:/testbench/TOP0/RAM0/datain
add wave -position end  sim:/testbench/TOP0/RAM0/dataout
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/flags
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/src_reg
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/dst_reg
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/read_memory
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/write_memory
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/aluop
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/CARRY_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_ORed
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/opcode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/src_mode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/dst_mode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/control_word
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/instruction
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/flags
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/MDR_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/MAR_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/IR_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/Z_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/Y_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/REGS_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/MDR_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/Z_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/REGS_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/SRC_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/DST_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/TMP_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/SRC_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/DST_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/TMP_OUT
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/src_reg
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/dst_reg
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/mdr_write_source
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/write_memory
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/aluop
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/CARRY_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/Flags_IN
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/CLR_Y
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_address
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f0
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_ORed
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_ORed1
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/next_ORed_final
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f1
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f10
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/opcode_ALU_operation
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/aluop_internal
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f2
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f3
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f4
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f6
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f1_decoded
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f2_decoded
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f3_decoded
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f4_decoded
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/f6_decoded
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/opcode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/src_mode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/dst_mode
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/BRANCH_CHECK
add wave -position end  sim:/testbench/TOP0/PDP/CONTROL_UNIT0/BRANCH
